name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Buildroot dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential wget cpio unzip rsync bc file \
            python3 python3-flake8 python3-matplotlib python3-pytest \
            libncurses5-dev libssl-dev cvs git mercurial subversion \
            subversion asciidoc w3m dblatex graphviz python3-pyparsing \
            libxml2-utils genisoimage libc6-i386

      - name: Run build script
        run: |
          cd snakeware
          chmod +x build.sh
          ./build.sh x86-64

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snakeware-iso
          path: snakeware/snakeware_x86-64.iso
          if-no-files-found: error
